title: ΤechnoΣημειωτική
author:
  name: Auli Viidalepp
  orcid: https://orcid.org/0000-0002-6206-5681

tagline: a research network and resource centre
description: >
  Technosemiotics bridges the studies 
  of technology, the environment, and the sociocultural sphere. 



# Build settings
baseurl: ""
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag


# excerpt_separator: <!--more-->

sass:
  quiet_deps: true
  silence_deprecations: [import]


minima:
  # Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: classic

  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - _pages/about.md
    - _pages/events.md
    - _pages/resources.md
    - _pages/concepts.md
    - _pages/references.md
    - _pages/critical-ai-scholars.md
  
  nav_pages_footer:
    - _pages/posts.md
    - _pages/events.md
    - _pages/categories.md

  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true

  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  date_format: "%A, %B %d, %Y"
  event_date_format: "%A, %B %d, %Y"
  event_time_format: "%H:%M %Z"

timezone: Europe/Tallinn

social:
    zenodo: "https://zenodo.org/communities/technosemiotics/"
    linkedin: "https://www.linkedin.com/company/technosemiotics"
    github: "https://github.com/technosemiotics"
    youtube: "https://www.youtube.com/@technosemiotics"
    instagram: "https://www.instagram.com/semiotictechnologies/"

# COLLECTIONS and DEFAULT settings ## TS ##

collections:
  pages:
    output: true
    permalink: /:name/
  events:
    output: true
    permalink: /events/:name/
    sort_by: start
  concepts:
    output: true
    permalink: /concepts/:name/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "concepts"
    values:
      layout: "concept"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "events"
    values:
      layout: "event"



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

